// <auto-generated />
using System;
using GameApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GameApi.Solution.Migrations
{
    [DbContext(typeof(GameApiContext))]
    [Migration("20220118231034_Player")]
    partial class Player
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("GameApi.Models.Cardigan", b =>
                {
                    b.Property<int>("CardiganId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("CardiganId");

                    b.ToTable("Cardigans");
                });

            modelBuilder.Entity("GameApi.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ItemId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("GameApi.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("EquippedCardiganCardiganId")
                        .HasColumnType("int");

                    b.Property<int?>("EquippedShoesShoeId")
                        .HasColumnType("int");

                    b.Property<int?>("HandItemItemId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("PlayerId");

                    b.HasIndex("EquippedCardiganCardiganId");

                    b.HasIndex("EquippedShoesShoeId");

                    b.HasIndex("HandItemItemId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("GameApi.Models.Shoe", b =>
                {
                    b.Property<int>("ShoeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ShoeId");

                    b.ToTable("Shoes");
                });

            modelBuilder.Entity("GameApi.Models.Player", b =>
                {
                    b.HasOne("GameApi.Models.Cardigan", "EquippedCardigan")
                        .WithMany()
                        .HasForeignKey("EquippedCardiganCardiganId");

                    b.HasOne("GameApi.Models.Shoe", "EquippedShoes")
                        .WithMany()
                        .HasForeignKey("EquippedShoesShoeId");

                    b.HasOne("GameApi.Models.Item", "HandItem")
                        .WithMany()
                        .HasForeignKey("HandItemItemId");

                    b.Navigation("EquippedCardigan");

                    b.Navigation("EquippedShoes");

                    b.Navigation("HandItem");
                });
#pragma warning restore 612, 618
        }
    }
}
